# This workflow is for a nightly run against RESTEasy upstream

name: RESTEasy Test Build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job and cancel previous ones
concurrency:
  group: 'resteasy-${{ github.ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  resteasy-build:
    uses: resteasy/resteasy/.github/workflows/shared-resteasy-build.yml@main
    with:
      resteasy-branch: "main"
      resteasy-repo: "resteasy/resteasy"

  resteasy-spring-build:
    runs-on: ${{ matrix.os }}
    needs: resteasy-build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: ['21']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: resteasy-maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzf resteasy-maven-repository.tar.gz -C ~
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }}
        run: mvn  -B clean install '-Dversion.org.jboss.resteasy=${{ needs.resteasy-build.outputs.resteasy-version }}'
      - name: Upload surefire reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      - name: Upload server logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/*.log'
